baseURL = "https://master.d3gpabo3zdttme.amplifyapp.com"
languageCode = "en-us"
title = "Spic'n Span Cleaners"

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Documents"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Environmental Cleanup Project"
  description = ""
  projectDescriptionTitle = "Project Description"
  projectDescriptionCopy = "The purpose of the project is to remove subsurface contamination related to releases from a former dry cleaner. Electrical resistance heating technology will be used to remediate the subsurface contamination. Cleanup will also facilitate future redevelopment of the Spic’N Span property."